project_name: kvmservice

builds:
  - binary: "opt/kubearmor/kvmservice"
    id: kvmservice
    goos:
      - linux
    goarch:
      - amd64

archives:
  - id: "kvmservice"
    builds:
      - "kvmservice"
    name_template: "{{.ProjectName}}_{{.Version}}_{{.Os}}-{{.Arch}}"
    files:
      - src: ./packaging/kvmservice.yaml
        dst: /opt/kvmservice
        strip_parent: true
      - src: ./packaging/kvmservice.service
        dst: /usr/lib/systemd/system
        strip_parent: true
      - src: ./karmor
        dst: /usr/local/bin

nfpms:
  - id: "kvmservice"
    builds:
      - "kvmservice"
    formats:
      - deb
      - rpm
    replaces:
      - kvmservice
    maintainer: "Eswar Rajan Subramanian <eswar@accuknox.com>"
    description: |
      Runtime Security Enforcement System for VM
    vendor: "kubearmor"
    homepage: "https://kubearmor.io"
    license: "Apache 2"
    file_name_template: "{{.ProjectName}}_{{.Version}}_{{.Os}}-{{.Arch}}"
    bindir: /
    contents:
      - dst: /opt/kubearmor
        type: dir
      - src: ./packaging/kvmservice.yaml
        dst: /opt/kubearmor/kvmservice.yaml
        type: config
      - src: ./packaging/kvmservice.service
        dst: /usr/lib/systemd/system/kvmservice.service
        type: config
      - src: /opt/kubearmor/kvmservice
        dst: /usr/local/bin/kvmservice
        type: symlink
      - src: ./karmor
        dst: /usr/local/bin/karmor
    scripts:
      postinstall: packaging/post-install.sh
