apiVersion: security.kubearmor.com/v1
kind: KubeArmorHostPolicy
metadata:
  name: khp-03
spec:
  nodeSelector:
    matchLabels:
      vm: enable
  severity: 5
  file:
    matchPaths:
    - path: /proc/cpuinfo
  action:
    Block
