apiVersion: v1
kind: ServiceAccount
metadata:
  name: kvmsoperator
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kvmsoperator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: kvmsoperator
  namespace: kube-system
---
apiVersion: v1
kind: Service
metadata:
  name: kvmsoperator
  namespace: kube-system
spec:
  selector:
    kvmsoperator-app: kvmsoperator
  ports:
  - port: 40400
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kvmsoperator
  namespace: kube-system
  labels:
    kvmsoperator-app: kvmsoperator
spec:
  selector:
    matchLabels:
      kvmsoperator-app: kvmsoperator
  template:
    metadata:
      labels:
        kvmsoperator-app: kvmsoperator
      annotations:
        container.apparmor.security.beta.kubernetes.io/kvmsoperator: unconfined
    spec:
      serviceAccountName: kvmsoperator
      nodeSelector:
        kubernetes.io/os: linux
      tolerations:
      - operator: Exists
      hostPID: true
      hostNetwork: true
      restartPolicy: Always
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: kvmsoperator
        image: seswarrajan/kvmsop:v0.5
        imagePullPolicy: Always
        securityContext:
          privileged: true
        env:
          - name: ETCD_NAMESPACE
            value: "kube-system"
        volumeMounts:
        - name: certs
          mountPath: /var/certs/
          readOnly: true
        - name: ca-cert
          mountPath: /var/ca-certs/
          readOnly: true
        - name: docker-sock-path # docker (read-only)
          mountPath: /var/run/docker.sock
          readOnly: true
        - name: usr-src-path # BPF (read-only)
          mountPath: /usr/src
          readOnly: true
        - name: lib-modules-path # BPF (read-only)
          mountPath: /lib/modules
          readOnly: true
        - name: sys-fs-bpf-path # BPF (read-write)
          mountPath: /sys/fs/bpf
        - name: sys-kernel-debug-path # BPF (read-write)
          mountPath: /sys/kernel/debug
            # - name: etc-apparmor-d-path # AppArmor (read-write)
            #   mountPath: /etc/apparmor.d
        - name: os-release-path # OS (read-only)
          mountPath: /media/root/etc/os-release
          readOnly: true
        livenessProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - |
              if [ -z $(pgrep kvmsoperator) ]; then
                exit 1;
              fi;
          initialDelaySeconds: 60
          periodSeconds: 10
        terminationMessagePolicy: File
        terminationMessagePath: /dev/termination-log
      terminationGracePeriodSeconds: 30
      volumes:
      - name: certs
        secret:
          secretName: server-certs
      - name: ca-cert
        secret:
          secretName: ca-cert
      - name: docker-sock-path # docker
        hostPath:
          path: /var/run/docker.sock
          type: Socket
      - name: usr-src-path # BPF
        hostPath:
          path: /usr/src
          type: Directory
      - name: lib-modules-path # BPF
        hostPath:
          path: /lib/modules
          type: Directory
      - name: sys-fs-bpf-path # BPF
        hostPath:
          path: /sys/fs/bpf
          type: Directory
      - name: sys-kernel-debug-path # BPF
        hostPath:
          path: /sys/kernel/debug
          type: Directory
            #- name: etc-apparmor-d-path # AppArmor
            #  hostPath:
            #    path: /etc/apparmor.d
            #    type: DirectoryOrCreate
      - name: os-release-path # OS
        hostPath:
          path: /etc/os-release
          type: File
